######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 10 04:51:24 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . build/CMakeFiles/CompilerIdC build/CMakeFiles/CompilerIdCXX
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
           build/CMakeFiles/CompilerIdC/CMakeCCompilerId.c \
           build/CMakeFiles/CompilerIdCXX/CMakeCXXCompilerId.cpp
