#ifndef MOD_TESTAPACHE_GLOBAL_H
#define MOD_TESTAPACHE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MOD_TESTAPACHE_LIBRARY)
#  define MOD_TESTAPACHESHARED_EXPORT Q_DECL_EXPORT
#else
#  define MOD_TESTAPACHESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MOD_TESTAPACHE_GLOBAL_H
