######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 3 02:56:15 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h \
    GUI.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp \
    GUI.cpp
