#ifndef TEXTFINDERLIB_GLOBAL_H
#define TEXTFINDERLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TEXTFINDERLIB_LIBRARY)
#  define TEXTFINDERLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TEXTFINDERLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TEXTFINDERLIB_GLOBAL_H
