### Makefile --- Sample Makefile for building a CPP apache2 module.

## Author: sonu@localhost
## Version: $Id: Makefile,v 0.0 2011/11/30 16:06:48 sonu Exp $
## Keywords: 
## X-URL: 

# Change this line as appropriate
APACHE_INCLUDE_PATH=/usr/include/apache-1.3

# These are the switches you should use, you may not want to put them
# in CPPFLAGS, you may want to specify them elsewhere. Just make sure
# they end up getting to the preprocessor when the time comes. These
# flags must appear _before_ any other -I flags.
CPPFLAGS = -I$(APACHE_INCLUDE_PATH) -I. -I-



